### ISSUE TITLE
pip install -r requirements.txt × Encountered error while generating package metadata.

### ISSUE THREAD

**Issue by fuzhexp** [lifuyi774/ProsperousPlus#1]
pip install -r requirements.txt

  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-2_z2ikb0/pymrmr_f2a124b187694f16b456b42bb1e36e07/setup.py", line 5, in <module>
          from Cython.Distutils import build_ext
      ModuleNotFoundError: No module named 'Cython'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Rvej** [comment]
Can you try to  install ”Cython" with “pip install Cython” and try again?
