### ISSUE TITLE
weka JAR dependency

### ISSUE THREAD

**Issue by TerenceChen95** [lifuyi774/ProsperousPlus#6]
Hi! I installed Java and export weka jar. Simply test with 
```
java weka.classifiers.meta.FilteredClassifier -p 16 -l finalModels/M10.014/M10.014_AODE_model -T results/predict.arff
```
and I got the following error: 
Weka exception: Unable to find class weka.classifiers.bayes.AveragedNDependenceEstimators.A1DE

I wonder if it is the weka version problem, plz help with the environment setting.

**Comment by Rvej** [comment]
Please try installing another JDK version, such as JDK1.8.

**Comment by TerenceChen95** [comment]
Thanks for reply! I've tried several version of Java(1.17, 1.22, 1.8) and all failed. Also, I tried to use the -classpath link to source/weka-3-9-3/weka.jar or the weka.jar installed, similar error indicating the weka.classifiers.meta.FilteredClassifier cannot be found
